In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pickle

In [5]:
df=pd.read_csv('./ipl/all_matches.csv')

df1=df[['match_id','season','venue','innings','striker','bowler','batting_team','bowling_team','ball','runs_off_bat','extras']]
df1=df1[(df1.ball != 0.7) & (df.ball != 0.8) & (df.ball != 0.9) & (df.ball != 1.8) & (df.ball != 2.8) & (df.ball != 3.8) & (df.ball != 4.8)
        & (df.ball != 1.7) & (df.ball != 2.7) & (df.ball != 3.7) & (df.ball != 4.7)  & (df.ball != 2.9) & (df.ball != 1.9)& (df.ball != 3.9)
       & (df.ball != 4.9)]

df1=df1.loc[(df1['ball'] < 5.7) & (df1['innings']<3)]
df1['total'] = df1['runs_off_bat'] + df1['extras']
df1.tail(20)





c:\python\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


match_id season                                     venue  innings  \
194245   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194246   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194247   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194248   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194249   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194250   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194251   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194252   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194253   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194254   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194255   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194256   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194257   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194258   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194259   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194260   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194261   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194262   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194263   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194264   1254060   2021  MA Chidambaram Stadium, Chepauk, Chennai        2   

            striker             bowler         batting_team  \
194245  JM Bairstow    Shakib Al Hasan  Sunrisers Hyderabad   
194246  JM Bairstow    Shakib Al Hasan  Sunrisers Hyderabad   
194247  JM Bairstow  M Prasidh Krishna  Sunrisers Hyderabad   
194248  JM Bairstow  M Prasidh Krishna  Sunrisers Hyderabad   
194249    MK Pandey  M Prasidh Krishna  Sunrisers Hyderabad   
194250  JM Bairstow  M Prasidh Krishna  Sunrisers Hyderabad   
194251    MK Pandey  M Prasidh Krishna  Sunrisers Hyderabad   
194252    MK Pandey  M Prasidh Krishna  Sunrisers Hyderabad   
194253  JM Bairstow    Shakib Al Hasan  Sunrisers Hyderabad   
194254  JM Bairstow    Shakib Al Hasan  Sunrisers Hyderabad   
194255  JM Bairstow    Shakib Al Hasan  Sunrisers Hyderabad   
194256    MK Pandey    Shakib Al Hasan  Sunrisers Hyderabad   
194257    MK Pandey    Shakib Al Hasan  Sunrisers Hyderabad   
194258    MK Pandey    Shakib Al Hasan  Sunrisers Hyderabad   
194259    MK Pandey         PJ Cummins  Sunrisers Hyderabad   
194260  JM Bairstow         PJ Cummins  Sunrisers Hyderabad   
194261  JM Bairstow         PJ Cummins  Sunrisers Hyderabad   
194262    MK Pandey         PJ Cummins  Sunrisers Hyderabad   
194263    MK Pandey         PJ Cummins  Sunrisers Hyderabad   
194264    MK Pandey         PJ Cummins  Sunrisers Hyderabad   

                 bowling_team  ball  runs_off_bat  extras  total  
194245  Kolkata Knight Riders   2.5             0       0      0  
194246  Kolkata Knight Riders   2.6             1       0      1  
194247  Kolkata Knight Riders   3.1             2       0      2  
194248  Kolkata Knight Riders   3.2             1       0      1  
194249  Kolkata Knight Riders   3.3             5       0      5  
194250  Kolkata Knight Riders   3.4             1       0      1  
194251  Kolkata Knight Riders   3.5             0       0      0  
194252  Kolkata Knight Riders   3.6             0       0      0  
194253  Kolkata Knight Riders   4.1             0       0      0  
194254  Kolkata Knight Riders   4.2             6       0      6  
194255  Kolkata Knight Riders   4.3             1       0      1  
194256  Kolkata Knight Riders   4.4             0       0      0  
194257  Kolkata Knight Riders   4.5             4       0      4  
194258  Kolkata Knight Riders   4.6             1       0      1  
194259  Kolkata Knight Riders   5.1     

In [6]:
df2=df1.groupby(['match_id','innings'])[['total']].sum().reset_index()
list=df2['total']
list1=[]
for i in range(0,list.size,1):
    for j in range(0,36,1):
        list1.append(list[i])
df2

match_id  innings  total
0       335982        1     54
1       335982        2     25
2       335983        1     53
3       335983        2     56
4       335984        1     34
...        ...      ...    ...
1631   1254058        2     44
1632   1254059        1     33
1633   1254059        2     65
1634   1254060        1     50
1635   1254060        2     35

[1636 rows x 3 columns]

In [7]:
df1['total_6']=list1[:58821]

In [8]:
df1



match_id   season                                     venue  innings  \
0         335982  2007/08                     M Chinnaswamy Stadium        1   
1         335982  2007/08                     M Chinnaswamy Stadium        1   
2         335982  2007/08                     M Chinnaswamy Stadium        1   
3         335982  2007/08                     M Chinnaswamy Stadium        1   
4         335982  2007/08                     M Chinnaswamy Stadium        1   
...          ...      ...                                       ...      ...   
194260   1254060     2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194261   1254060     2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194262   1254060     2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194263   1254060     2021  MA Chidambaram Stadium, Chepauk, Chennai        2   
194264   1254060     2021  MA Chidambaram Stadium, Chepauk, Chennai        2   

            striker      bowler           batting_team  \
0        SC Ganguly     P Kumar  Kolkata Knight Riders   
1       BB McCullum     P Kumar  Kolkata Knight Riders   
2       BB McCullum     P Kumar  Kolkata Knight Riders   
3       BB McCullum     P Kumar  Kolkata Knight Riders   
4       BB McCullum     P Kumar  Kolkata Knight Riders   
...             ...         ...                    ...   
194260  JM Bairstow  PJ Cummins    Sunrisers Hyderabad   
194261  JM Bairstow  PJ Cummins    Sunrisers Hyderabad   
194262    MK Pandey  PJ Cummins    Sunrisers Hyderabad   
194263    MK Pandey  PJ Cummins    Sunrisers Hyderabad   
194264    MK Pandey  PJ Cummins    Sunrisers Hyderabad   

                       bowling_team  ball  runs_off_bat  extras  total  \
0       Royal Challengers Bangalore   0.1             0       1      1   
1       Royal Challengers Bangalore   0.2             0       0      0   
2       Royal Challengers Bangalore   0.3             0       1      1   
3       Royal Challengers Bangalore   0.4             0       0      0   
4       Royal Challengers Bangalore   0.5             0       0      0   
...                             ...   ...           ...     ...    ...   
194260        Kolkata Knight Riders   5.2             0       0      0   
194261        Kolkata Knight Riders   5.3             1       0      1   
194262        Kolkata Knight Riders   5.4             0       0      0   
194263        Kolkata Knight Riders   5.5             0       0      0   
194264        Kolkata Knight Riders   5.6             1       0      1   

        total_6  
0            54  
1            54  
2            54  
3            54  
4            54  
...         ...  
194260       65  
194261       65  
194262       65  
194263       65  
194264       65  

[58821 rows x 13 columns]

In [33]:
df3=df1[['venue','season','ball','innings','striker','bowler','batting_team','bowling_team','total_6']]
df3['batting_team'].unique()


array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Chennai Super Kings', 'Kings XI Punjab', 'Rajasthan Royals',
       'Delhi Daredevils', 'Deccan Chargers', 'Mumbai Indians',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [20]:
team_encoding={'Mumbai Indians':1,
              'Royal Challengers Bangalore':2,
              'Kolkata Knight Riders':3,
              'Kings XI Punjab':4,
              'Chennai Super Kings':5,
              'Rajasthan Royals':6,
              'Delhi Daredevils':7,
              'Sunrisers Hyderabad':8,
              'Deccan Chargers':9,
              'Pune Warriors':10,
              'Delhi Capitals':11,
              'Gujarat Lions':12,
              'Rising Pune Supergiants':13,
              'Rising Pune Supergiant':13,
              'Kochi Tuskers Kerala':14}
team_encode_dict={'batting_team':team_encoding,
                 'bowling_team':team_encoding}
df3.replace(team_encode_dict,inplace=True)
df3


c:\python\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


venue   season  ball  innings  \
0                          M Chinnaswamy Stadium  2007/08   0.1        1   
1                          M Chinnaswamy Stadium  2007/08   0.2        1   
2                          M Chinnaswamy Stadium  2007/08   0.3        1   
3                          M Chinnaswamy Stadium  2007/08   0.4        1   
4                          M Chinnaswamy Stadium  2007/08   0.5        1   
...                                          ...      ...   ...      ...   
194260  MA Chidambaram Stadium, Chepauk, Chennai     2021   5.2        2   
194261  MA Chidambaram Stadium, Chepauk, Chennai     2021   5.3        2   
194262  MA Chidambaram Stadium, Chepauk, Chennai     2021   5.4        2   
194263  MA Chidambaram Stadium, Chepauk, Chennai     2021   5.5        2   
194264  MA Chidambaram Stadium, Chepauk, Chennai     2021   5.6        2   

            striker      bowler  batting_team  bowling_team  total_6  
0        SC Ganguly     P Kumar             3             2       54  
1       BB McCullum     P Kumar             3             2       54  
2       BB McCullum     P Kumar             3             2       54  
3       BB McCullum     P Kumar             3             2       54  
4       BB McCullum     P Kumar             3             2       54  
...             ...         ...           ...           ...      ...  
194260  JM Bairstow  PJ Cummins             8             3       65  
194261  JM Bairstow  PJ Cummins             8             3       65  
194262    MK Pandey  PJ Cummins             8             3       65  
194263    MK Pandey  PJ Cummins             8             3       65  
194264    MK Pandey  PJ Cummins             8             3       65  

[58821 rows x 9 columns]

In [34]:
from sklearn import preprocessing
ftr_list=['bowler']
encoder=preprocessing.LabelEncoder()
for ftr in ftr_list:
    df3[ftr]=encoder.fit_transform(df3[ftr])
    x=encoder.classes_
print(x)



['A Ashish Reddy' 'A Chandila' 'A Choudhary' 'A Dananjaya' 'A Flintoff'
 'A Kumble' 'A Mishra' 'A Mithun' 'A Nehra' 'A Nel' 'A Nortje' 'A Singh'
 'A Symonds' 'A Uniyal' 'A Zampa' 'AA Chavan' 'AA Jhunjhunwala'
 'AA Noffke' 'AB Agarkar' 'AB Dinda' 'AB McDonald' 'AC Thomas' 'AC Voges'
 'AD Mascarenhas' 'AD Mathews' 'AD Russell' 'AF Milne' 'AG Murtaza'
 'AJ Finch' 'AJ Tye' 'AL Menaria' 'AM Nayar' 'AM Salvi' 'AN Ahmed'
 'AP Dole' 'AR Patel' 'AS Joseph' 'AS Rajpoot' 'Anand Rajan'
 'Ankit Sharma' 'Ankit Soni' 'Anureet Singh' 'Arshdeep Singh' 'Avesh Khan'
 'Azhar Mahmood' 'B Akhil' 'B Geeves' 'B Kumar' 'B Laughlin' 'B Lee'
 'B Stanlake' 'BA Bhatt' 'BA Stokes' 'BAW Mendis' 'BB Sran' 'BCJ Cutting'
 'BE Hendricks' 'BJ Hodge' 'BW Hilfenhaus' 'Basil Thampi' 'Bipul Sharma'
 'C de Grandhomme' 'CH Gayle' 'CH Morris' 'CJ Anderson' 'CJ Dala'
 'CJ Green' 'CJ Jordan' 'CJ McKay' 'CK Langeveldt' 'CR Brathwaite'
 'CR Woakes' 'CRD Fernando' 'CV Varun' 'D Wiese' 'D du Preez'
 'DAJ Bracewell' 'DE Bollinger' 'DJ

<ipython-input-34-525f9e93b257>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3[ftr]=encoder.fit_transform(df3[ftr])


In [14]:
df3

venue   season  ball  innings      striker      bowler  batting_team  \
0          15  2007/08   0.1        1   SC Ganguly     P Kumar             3   
1          15  2007/08   0.2        1  BB McCullum     P Kumar             3   
2          15  2007/08   0.3        1  BB McCullum     P Kumar             3   
3          15  2007/08   0.4        1  BB McCullum     P Kumar             3   
4          15  2007/08   0.5        1  BB McCullum     P Kumar             3   
...       ...      ...   ...      ...          ...         ...           ...   
194260     19     2021   5.2        2  JM Bairstow  PJ Cummins             8   
194261     19     2021   5.3        2  JM Bairstow  PJ Cummins             8   
194262     19     2021   5.4        2    MK Pandey  PJ Cummins             8   
194263     19     2021   5.5        2    MK Pandey  PJ Cummins             8   
194264     19     2021   5.6        2    MK Pandey  PJ Cummins             8   

        bowling_team  total_6  
0                  2       54  
1                  2       54  
2                  2       54  
3                  2       54  
4                  2       54  
...              ...      ...  
194260             3       65  
194261             3       65  
194262             3       65  
194263             3       65  
194264             3       65  

[58821 rows x 9 columns]

In [33]:
from sklearn.model_selection import train_test_split
X = df3[['venue','innings','batting_team','bowling_team','striker','bowler']]
y=df3['total_6'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=6)

In [40]:
#Knn Regression 

In [34]:
from sklearn.neighbors import KNeighborsClassifier
# Create KNN classifier
knn = KNeighborsClassifier(n_neighbors = 5)
# Fit the classifier to the data
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [35]:
#show first 5 model predictions on the test data
knn.predict(X_test)


array([57, 45, 37, ..., 50, 24, 47], dtype=int64)

In [36]:
knn.score(X_test, y_test)

0.602804929876753

In [37]:
y_pred = knn.predict([[11,1,7,1,37,223]])
y_pred

array([54], dtype=int64)

In [42]:
# Random forest regression

SyntaxError: invalid syntax (<ipython-input-42-a346336a5b94>, line 1)

In [48]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 100, random_state = 4)
rf.fit(X_train,y_train)

RandomForestRegressor(random_state=4)

In [49]:
rf.predict(X_test)

array([57.06      , 41.3953438 , 44.66511544, ..., 52.2325    ,
       49.15      , 47.201     ])

In [50]:
rf.score(X_test,y_test)

0.75492488920772

In [52]:
y_pred=rf.predict([[11,1,7,1,37,223]])
y_pred

array([40.49235354])

In [53]:
#Ridge Regression

In [66]:
from sklearn.linear_model import Ridge
model = Ridge(alpha = 1.0, normalize = False, tol = 1.0,
              solver ='auto', random_state = 21)
model.fit(X_train, y_train)

Ridge(random_state=21, tol=1.0)

In [67]:
model.score(X_test,y_test)

0.0030517983061890686